--
-- PostgreSQL database dump
--

-- Dumped from database version 17.0
-- Dumped by pg_dump version 17.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: app_users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_users (
    id bigint NOT NULL,
    username character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL
);


ALTER TABLE public.app_users OWNER TO postgres;

--
-- Name: app_users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.app_users_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.app_users_id_seq OWNER TO postgres;

--
-- Name: app_users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.app_users_id_seq OWNED BY public.app_users.id;


--
-- Name: applications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.applications (
    id bigint NOT NULL,
    applied_date timestamp(6) without time zone,
    cover_letter text,
    resume_url character varying(255),
    status character varying(255),
    job_id bigint NOT NULL,
    teacher_id bigint NOT NULL
);


ALTER TABLE public.applications OWNER TO postgres;

--
-- Name: applications_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.applications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.applications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: employer_profiles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employer_profiles (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    company_name character varying(255) NOT NULL,
    company_description text,
    website character varying(255),
    logo_url character varying(255)
);


ALTER TABLE public.employer_profiles OWNER TO postgres;

--
-- Name: employer_profiles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.employer_profiles_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.employer_profiles_id_seq OWNER TO postgres;

--
-- Name: employer_profiles_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.employer_profiles_id_seq OWNED BY public.employer_profiles.id;


--
-- Name: job; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.job (
    approved boolean NOT NULL,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    apply_info character varying(255),
    category character varying(255) NOT NULL,
    company character varying(255) NOT NULL,
    description text NOT NULL,
    location character varying(255),
    salary_range character varying(255),
    title character varying(255) NOT NULL,
    work_type character varying(255)
);


ALTER TABLE public.job OWNER TO postgres;

--
-- Name: job_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.job ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.job_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: jobs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.jobs (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    company character varying(255) NOT NULL,
    location character varying(255),
    salary_range character varying(255),
    description text,
    approved boolean DEFAULT false,
    category character varying(255),
    work_type character varying(255),
    apply_info character varying(255),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    employer_id bigint
);


ALTER TABLE public.jobs OWNER TO postgres;

--
-- Name: jobs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.jobs_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.jobs_id_seq OWNER TO postgres;

--
-- Name: jobs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.jobs_id_seq OWNED BY public.jobs.id;


--
-- Name: teacher; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.teacher (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    bio text,
    desired_role character varying(255),
    full_name character varying(255),
    subject_specialty character varying(255),
    years_in_classroom integer,
    profile_image_url character varying(255),
    resume_url character varying(255),
    public_profile boolean
);


ALTER TABLE public.teacher OWNER TO postgres;

--
-- Name: teacher_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.teacher ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.teacher_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: teacher_saved_jobs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.teacher_saved_jobs (
    teacher_id bigint NOT NULL,
    job_id bigint NOT NULL
);


ALTER TABLE public.teacher_saved_jobs OWNER TO postgres;

--
-- Name: app_users id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_users ALTER COLUMN id SET DEFAULT nextval('public.app_users_id_seq'::regclass);


--
-- Name: employer_profiles id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employer_profiles ALTER COLUMN id SET DEFAULT nextval('public.employer_profiles_id_seq'::regclass);


--
-- Name: jobs id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jobs ALTER COLUMN id SET DEFAULT nextval('public.jobs_id_seq'::regclass);


--
-- Data for Name: app_users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.app_users (id, username, password, role) FROM stdin;
1	admin	$2a$10$o3tcLfy1Foh5C8tJX.xF9.XlxZWvPDJFWKry2886CUpDskH0c6jxS	ADMIN
2	acme@asdf.com	$2a$10$Oli6R30u5HwcQxZTO58oj.xAYQLFW5n75j2bbfxhxZqmTvXciABqi	EMPLOYER
3	edtech_inc	$2a$10$UIiYrZQ7IBJx2AoJTHrZfeJS3w2IFN2nXlmxMWqPUFiyvfQalSM0C	EMPLOYER
4	cooljohnny@gmai.com	$2a$10$h7IEKs6AM9qFWVdRqM9V4OOD7PwN06vXDvfqm2abQdS.WZFLq2Knu	EMPLOYER
6	tkarmes@gmail.com	$2a$10$P9lSboabMPkrY1hdsJ5jCu91CFTnPsmPNiiGHUT7Qhr2oXGGyDEky	EMPLOYER
7	Teacher1@gmail.com	$2a$10$1ATKzNvgWDCOnSbwas9Kz.iUjQdRnV40vR6Qn4InwIjXHpuog5bMu	TEACHER
8	Teacher2@gmail.com	$2a$10$kWiUiYSZbgIotdVfT.0PrOOLSc3nJdckLWwcsNrBaqei9NxVefKiq	TEACHER
9	employer1@gmail.com	$2a$10$3thD9G1o/d57lrVUer.PJeoVZVnGnB8pLDya3EFUHRieglhBbjXSu	EMPLOYER
10	Teacher3@gmail.com	$2a$10$QJsu6BtcvJ5Xn20gVY9.te4LUeI7OvDH7tPdP/U5SSF.olvrTLJnu	TEACHER
11	employer3@gmail.com	$2a$10$mbTqBypxccP0udDYi0WHlO/L6M/dK8lbcVEm9lAz5aDdAfrB6nri6	EMPLOYER
\.


--
-- Data for Name: applications; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.applications (id, applied_date, cover_letter, resume_url, status, job_id, teacher_id) FROM stdin;
2	2026-04-14 21:03:20.834231	\N	/uploads/f45f5cf7-0f0f-4316-a76e-b0fdbfb53605.pdf	PENDING	7	2
3	2026-04-14 21:07:23.042883	\N	/uploads/5cf2b345-f304-4ec8-bdce-83ad12f4ac13.pdf	PENDING	4	1
4	2026-04-14 21:08:10.436743	\N	/uploads/f45f5cf7-0f0f-4316-a76e-b0fdbfb53605.pdf	PENDING	4	2
\.


--
-- Data for Name: employer_profiles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.employer_profiles (id, user_id, company_name, company_description, website, logo_url) FROM stdin;
1	2	Acme Brick Inc.	we build	https://github.com/tkarmes	\N
2	3	EdTech Solutions Inc.	Leading the way in classroom technology.	https://example.com	\N
3	4	Acme Brick Inc.	we say hello for you	https://github.com/tkarmes	\N
4	6	Hardee	Go set the world on fire!!	www.webrousers.com	https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png
6	11	Grouchy Old Lady Cleaners	We clean grouchy old ladies places and their nasty cat litter.	www.webrousers.com	/images/logos/cbcefe82-03e0-41f5-a9d7-710253f4ca84.jpg
5	9	DaisyDukes	Short shorts. Because skin is in!	www.webrousers.com	/uploads/e915743c-f2c7-4956-9cb7-b38209a1e969.jpg
\.


--
-- Data for Name: job; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.job (approved, created_at, id, apply_info, category, company, description, location, salary_range, title, work_type) FROM stdin;
t	2026-03-23 17:45:59.981909	2	www.hrjobs.com	EdTech	Allen Eagles	hr stuff	Allen, TX	45,000	HR 	Full Time
t	2026-03-23 19:47:46.373459	3	www.hr.com	Customer Education	Acme Brick	test	New York, NY	75,000-90-000	Test Job 2	Full Time
t	2026-03-23 21:11:22.579265	4	www.hr.com	Other	Hardeeee	<p>Get bossed around by Eric the Annoying.</p>	Austin, TX	75,000-90-000	Journeyman Electrician	Full Time
t	2026-03-24 14:10:40.033894	5	tkarmes@gmail.com	Instructional Design	Acme	<p>long work long time</p>	San Fransico, CA	75,000-90-000	Full Stack Dev	Full Time
t	2026-03-24 14:12:16.37671	7	tkarmes@gmail.com	Other	Gene Roy	<p>assdfasdf</p>	East Texas	77K	Plumber	Contract
\.


--
-- Data for Name: jobs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.jobs (id, title, company, location, salary_range, description, approved, category, work_type, apply_info, created_at, employer_id) FROM stdin;
1	Learning Experience Designer	EdTech Solutions Inc.	Remote	$70k - $90k	We are looking for former teachers to help design engaging digital curriculum.	t	EdTech	Full-time	Apply at jobs@example.com	2026-03-28 00:51:09.419242	2
2	Customer Success Manager	EdTech Solutions Inc.	New York, NY	$65k - $85k	Support school districts in implementing our platform. Classroom experience highly valued!	t	Sales/Success	Full-time	Apply on our website.	2026-03-28 00:51:09.432787	2
3	Electrician	Hardeeee	Austin, TX	75,000-90-000	testing	t	Other	Full-time	www.hr.com	2026-03-28 14:29:01.091547	2
4	History Center	Texas State	Austin, TX	$80,000	Davy Crocket freaks only apply!	t	Other	Full-time	www.webrousers.com	2026-03-31 20:04:58.016483	4
7	California Homeless Assistant	WeBuyHomelessness	San Fransico, CA	$1,000,000,000 in tax payer money	Take money to help solve the homeless crisis allotted by the state of California and do nothing with it.	t	Other	Contract	www.webrousers.com	2026-04-02 08:08:25.797752	4
8	Elctrician	Hardeeee	Austin, TX	75,000-90-000	Electrify the world with us!	t	Other	Full-time	www.webrousers.com	2026-04-04 14:34:42.611058	4
9	Day Care Worker	Learing Center	Minneapolis, MN	1 billion dollars	Scam the state and feds!	t	Other	Full-time	www.webrousers.com	2026-04-18 11:03:33.954895	4
6	Daycare Attendent	Learing Center	Minneapolis, MN	$1,000,000,000	Do nothing on the idiot American tax payers dime. Somali's only apply!!! Whites need not apply. This is a racist post and cannot get by admin on an update.	t	Other	Full-time	www.webrousers.com	\N	4
10	Dry Wall	Wall Hall and Ball	Austin, TX	75,000-90-000	Build baby build	t	Other	Full-time	www.webrousers.com	2026-04-20 11:34:35.770949	4
11	Testing Post!!!	Acme	Austin, TX	75,000-90-000	asdfasdfasdf	f	Other	Freelance	webrousers.com	2026-05-21 16:33:17.394569	5
\.


--
-- Data for Name: teacher; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.teacher (id, user_id, bio, desired_role, full_name, subject_specialty, years_in_classroom, profile_image_url, resume_url, public_profile) FROM stdin;
1	7	I'm not as steady as I once was but I'm as steady now as I'll ever be.	Surgeon	Broken Hand	High School Anatomy	5	/uploads/0ddb0b52-ae8f-4c10-ad40-7ceb72433dbd.jpg	/uploads/5cf2b345-f304-4ec8-bdce-83ad12f4ac13.pdf	t
3	10	I need out badly.	Open to See	Red Rocks	General Education	5	/uploads/3140ac32-421b-4e05-b7c5-104439b38f81.jpg	/uploads/51e23960-c152-45fb-aa7a-4b240c20fa2d.pdf	t
2	8	Ive been here and Ive been there and Ive been everywhere. 	Electrician	Eric Hardly	High School Spitballer	5	/uploads/a11f3da1-174e-4161-a190-bebfa9d6f35e.png	/uploads/f45f5cf7-0f0f-4316-a76e-b0fdbfb53605.pdf	t
\.


--
-- Data for Name: teacher_saved_jobs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.teacher_saved_jobs (teacher_id, job_id) FROM stdin;
1	7
1	6
2	8
2	1
1	1
1	8
\.


--
-- Name: app_users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.app_users_id_seq', 11, true);


--
-- Name: applications_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.applications_id_seq', 4, true);


--
-- Name: employer_profiles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.employer_profiles_id_seq', 6, true);


--
-- Name: job_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.job_id_seq', 7, true);


--
-- Name: jobs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.jobs_id_seq', 11, true);


--
-- Name: teacher_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.teacher_id_seq', 3, true);


--
-- Name: app_users app_users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_users
    ADD CONSTRAINT app_users_pkey PRIMARY KEY (id);


--
-- Name: app_users app_users_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_users
    ADD CONSTRAINT app_users_username_key UNIQUE (username);


--
-- Name: applications applications_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.applications
    ADD CONSTRAINT applications_pkey PRIMARY KEY (id);


--
-- Name: employer_profiles employer_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employer_profiles
    ADD CONSTRAINT employer_profiles_pkey PRIMARY KEY (id);


--
-- Name: job job_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job
    ADD CONSTRAINT job_pkey PRIMARY KEY (id);


--
-- Name: jobs jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT jobs_pkey PRIMARY KEY (id);


--
-- Name: teacher teacher_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teacher
    ADD CONSTRAINT teacher_pkey PRIMARY KEY (id);


--
-- Name: teacher_saved_jobs teacher_saved_jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teacher_saved_jobs
    ADD CONSTRAINT teacher_saved_jobs_pkey PRIMARY KEY (teacher_id, job_id);


--
-- Name: teacher uki5wqs2ds2vpmfpbcdxi9m2jvr; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teacher
    ADD CONSTRAINT uki5wqs2ds2vpmfpbcdxi9m2jvr UNIQUE (user_id);


--
-- Name: employer_profiles employer_profiles_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employer_profiles
    ADD CONSTRAINT employer_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(id);


--
-- Name: applications fk65weib1lru9dkrbto5pv389vi; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.applications
    ADD CONSTRAINT fk65weib1lru9dkrbto5pv389vi FOREIGN KEY (job_id) REFERENCES public.jobs(id);


--
-- Name: teacher fkcvxj2xomtny71odd3b3ytqjt7; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teacher
    ADD CONSTRAINT fkcvxj2xomtny71odd3b3ytqjt7 FOREIGN KEY (user_id) REFERENCES public.app_users(id);


--
-- Name: applications fkrkd9cemvmv62qqbica56e3opc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.applications
    ADD CONSTRAINT fkrkd9cemvmv62qqbica56e3opc FOREIGN KEY (teacher_id) REFERENCES public.teacher(id);


--
-- Name: teacher_saved_jobs fkrqcuqbtdhgk4t6yeb9rjupwjy; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teacher_saved_jobs
    ADD CONSTRAINT fkrqcuqbtdhgk4t6yeb9rjupwjy FOREIGN KEY (job_id) REFERENCES public.jobs(id);


--
-- Name: teacher_saved_jobs fkspkclewi3e6qbhwmdql9jvxp3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teacher_saved_jobs
    ADD CONSTRAINT fkspkclewi3e6qbhwmdql9jvxp3 FOREIGN KEY (teacher_id) REFERENCES public.teacher(id);


--
-- Name: jobs fksyxvoyuaq6bwaxh4qi8v4m02l; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT fksyxvoyuaq6bwaxh4qi8v4m02l FOREIGN KEY (employer_id) REFERENCES public.employer_profiles(id);


--
-- PostgreSQL database dump complete
--

