# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# THYMELEAF
# ===============================
spring.thymeleaf.cache=false

# ===============================
# DATABASE
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/formerteachersdb
spring.datasource.username=postgres
spring.datasource.password=postgres1

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# SPRINGDOC / SWAGGER
# ===============================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui/