spring.application.name=FormerTeachers
spring.datasource.url=jdbc:postgresql://localhost:5432/formerteachersdb
spring.datasource.username=postgres
spring.datasource.password=postgres1
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always
