# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# THYMELEAF
# ===============================
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.enabled=true
spring.thymeleaf.check-template-location=true

# ===============================
# DATABASE
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/formerteachersdb

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# SPRINGDOC / SWAGGER
# ===============================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui/

# ===============================
# GREENHOUSE API
# ===============================
greenhouse.api.url=https://boards-api.greenhouse.io/v1/boards/YOUR_COMPANY/jobs
greenhouse.api.key=   # optional, only if your API requires a key


spring.web.resources.static-locations=classpath:/css/,classpath:/static/,classpath:/public/

# Admin Credentials

spring.config.import=optional:classpath:secrets.properties